apiVersion: v1
kind: Service
metadata:
  name: postgres-local
  namespace: local
  labels:
    app: postgres-local
    environment: local
spec:
  type: ClusterIP
  selector:
    app: postgres-local
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
    protocol: TCP
