apiVersion: v1
kind: Service
metadata:
  name: redis-local
  namespace: local
  labels:
    app: redis-local
    environment: local
spec:
  type: ClusterIP
  selector:
    app: redis-local
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
